---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  
  tasks:
  
     tasks:
    - name: ensure the java apt repository key is installed
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
      become: yes

    - name: ensure the repository is configured
      apt_repository: repo='deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main' state=present
      become: yes

      
  
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
           - openjdk-11-jdk
           
          
    - name: Install Maven using ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
           - maven 
        
